name: app_review_example
description: Demonstrates how to use the app_review plugin.

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '3.10.6'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  app_review:
    path: ../

flutter:
  uses-material-design: true
